#!/bin/bash

grep "^-" $1 > vf_typescript_original.txt
grep "^-" $2 > vf_typescript_modificat.txt


echo "Fisiere sterse: "
for fisier in $(awk '{print $9}' "vf_typescript_original.txt") ;
do
rezultat=$(grep -w "$fisier" vf_typescript_modificat.txt)
if [[ ! -n $rezultat ]]; then
echo "$fisier"
fi
done
echo "############################"

######################################

echo "Fisiere adaugate:"
for fisier in $(awk '{print $9}' "vf_typescript_modificat.txt") ;
do
rezultat=$(grep -w "$fisier" vf_typescript_original.txt)
if [[ ! -n $rezultat ]]; then
echo "$fisier"
fi
done
echo "############################"

################################################################################

echo "Modificatii: "
echo ""
######################################

for fisier in $(awk '{print $9}' "vf_typescript_original.txt") ;
do
aparitie_fisier=0
rezultat=$(grep -w "$fisier" vf_typescript_modificat.txt)
#adauga proprietatile fisierului nou in variabila rezultat
cuvinte_rezultat=($rezultat)
#transforma propozitia din rezultat intr un array de cuvinte in cuvinte_rezultat

if [[ -n $rezultat ]]; then    
#verifica daca exista fisierul; daca variabila rezultat e goala sau nu

original=$(grep -w "$fisier" vf_typescript_original.txt)
#adauga proprietatile fisierului vechi in variabila original

c=0 #variabila contor pentru fisierul modificat
for i in $original
do
if [[ $i != ${cuvinte_rezultat[$c]} ]]; then
if [[ $aparitie_fisier == 0 ]]; then
echo $fisier
echo ""
echo -n "modificare "
aparitie_fisier=1
fi
case "$c" in
0)
echo  "permisiune din $i in ${cuvinte_rezultat[$c]}" ;;
1)
echo  "numar de linkuri din $i in ${cuvinte_rezultat[$c]}" ;;
2)
echo  "proprietar fisier din $i in ${cuvinte_rezultat[$c]}" ;;
3)
echo  "grup fisierdin $i in ${cuvinte_rezultat[$c]}" ;;
4)
echo  "dimensiune fisier din $i in ${cuvinte_rezultat[$c]}" ;;
S*)
continue ;;
esac
fi
((c++))
done

fi
if [[ $aparitie_fisier == 1 ]]; then
echo "############################"
aparitie_fisier=0
fi
done



> vf_typescript_original.txt
> vf_typescript_modificat.txt
vftext=0
lin=2
for i in $(awk '{print $3}' typescript_original.txt) ;
do

if [[ ! "$i" =~ ^[0-9]+$ && $vftext == 1 ]]; then
break
fi
if [[ $vftext == 1 ]]; then
awk -v n=$lin 'NR==n {print $0}' typescript_original.txt >> vf_typescript_original.txt

fi
if [ $i = "Used" ]; then
vftext=1
fi
((lin++))
done
vftext=0
lin=2
for i in $(awk '{print $3}' typescript_modificat.txt) ;
do

if [[ ! "$i" =~ ^[0-9]+$ && $vftext == 1 ]]; then
break
fi
if [[ $vftext == 1 ]]; then
awk -v n=$lin 'NR==n {print $0}' typescript_modificat.txt >> vf_typescript_modificat.txt

fi
if [ $i = "Used" ]; then
vftext=1
fi
((lin++))
done


echo "Spatiu: "
i=1
while read -r linie; do
linie=($linie)
if [[ ${linie[2]} != $(awk -v n=$i 'NR==n {print $3}' vf_typescript_modificat.txt) ]]; then

echo -n "${linie[0]} si-a schimbat spatiul din ${linie[2]} KB in $(awk -v n=$i 'NR==n {print $3}' vf_typescript_modificat.txt) KB"

echo "si au mai ramas $(awk -v n=$i 'NR==n {print $4}' vf_typescript_modificat.txt) KB in loc de ${linie[3]} KB"
fi



((i++))
done < vf_typescript_original.txt
